### ISSUE TITLE
loadbalance the request from an ipv6 host to the backend IPv4 nodes

### ISSUE THREAD

**Issue by GeorgeGuo2018** [iccfish/PortProxy#1]
can I do something like this，The node which PortProxy was running on have both IPv4 and IPv6 address(suppose they are IPv4B + IPv6B）; Behind the PortProxy node,there exist three hosts each has a service running on. Those three nodes are  IPv4 only(suppose their IPs are IPv4C, IPv4D and IPv4E,   IPv4 B to IPv4E are under the same subnet).

Now I want to use the PortProxy node as an LB node,  for example, if i request for IPv6B:9000,i get to  IPv4C, and when i reuqest for IPv6B:9001,i get to IPv4D. Something like this.(suppose the client is IPv6 only)

**Comment by iccfish** [comment]
Please consider using [PortProxyV2](https://github.com/iccfish/PortProxyV2) which was newer and under development.

Please give me more information about your request...I don't quite understand :-)

**Comment by GeorgeGuo2018** [comment]
Hi, iccfish, Thanks for your reply.  The demand is something like Netsh v6tov4 or NAT64.  But NAT64 need to work with DNS64, the client should be redirect to the dedicated DNS64 server, which is usually not reasonable requirement  in product environment.

**Comment by iccfish** [comment]
To make me clear, can you cite a case please?

**Comment by GeorgeGuo2018** [comment]
Hi,iccfish. Suppose such a topology as follows:
client node(ip address 2001:4:if:98::1)    
LB node(ip address2001:4:if:98::2 and 192.168.0.1)  
ServiceA node(ip address 192.168.0.2)
ServiceB node(ip address 192.168.0.2)


now,i want to access to ServiceA or ServiceB from the client, which has only IPv6 address. 
Did i make it clear to you?

**Comment by GeorgeGuo2018** [comment]
Did you have any good idea?

Seems that PortProxyV2 mainly used as an tunnel, i am not sure whether I can use it to transfer IPv6 package header to IPv4 header,  will check.

**Comment by iccfish** [comment]
Emmm.....PortProxy can only use as a tunnel, can't be used as load balancing, and it's primary target was to provide a secure & obfuscated tunnel to passthrough some **strange** firewall.

If your network service was http, nginx would works better.

Or, you can have a look at [frp](https://github.com/fatedier/frp#load-balancing), a powerful reverse proxy.

**Comment by GeorgeGuo2018** [comment]
> Emmm.....PortProxy can only use as a tunnel, can't be used as load balancing, and it's primary target was to provide a secure & obfuscated tunnel to passthrough some **strange** firewall.
> 
> If your network service was http, nginx would works better.
> 
> Or, you can have a look at [frp](https://github.com/fatedier/frp#load-balancing), a powerful reverse proxy.

Thanks for your suggest. Really appreciate it.
